name: Scheule Workflow

on:
  schedule:
    - cron: "* * * * *" # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
