name: Workflow with approval

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo "Building the project..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://production-url.com
    steps:
      - name: Deploy
        run: echo "Deploying the project..."
