name: Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "Description for input1"
        required: true
      input2:
        description: "Description for input2"
        required: false
        default: "default value for input2"

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        run: |
          echo "Input1: ${{ github.event.inputs.input1 }}"
          echo "Input2: ${{ github.event.inputs.input2 }}"

  call-workflow:
    uses: meet96/workflow-core/.github/workflows/workflow-core-inputs.yml@main
    with:
      input1: ${{ github.event.inputs.input1 }}
      input2: ${{ github.event.inputs.input2 }}
  call-workflow2:
    uses: meet96/workflow-core/.github/workflows/workflow-core-switch-case.yml@main
    with:
      input1: ${{ github.event.inputs.input1 }}
      input2: ${{ github.event.inputs.input2 }}
